export type TParametricErrors = "INVALID_INPUT" | "RESOURCE_EXISTS" | "INVALID_CREDENTIALS" | "RESOURCE_NOT_FOUND";

export type TNonParametricErrors = "NOT_SIGNEDIN" | "RESOURCE_EXISTS" | "NOT_ALLOWED_ACCESS" | "RESOURCE_NOT_FOUND";